server:
  port: 8001
spring:
  application:
    name: gateway
  #配置跨域
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':  #匹配所有请求
            allowedOragins: "*" #跨域处理，允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #id:给路由一个唯一的名称
        - id: changgou-brand-route
         #用户请求需要路由到哪个服务器
         #lb:使用loadBalancer实现负载均衡，注意需要写注册的微服务集群的注册名称
          uri: lb://goods
          #路由断言，路由规则配置
          predicates:
          #用户请求的域名规则配置
          # - Host= cg.search/**
          #；路径配置及：所有brand请求路径开始的都路由到老localhost:18085去
          - Path=/api/brand/**
          # 请求时需要输入/api/cg.search路径开头请求路由到localhost:18085，但是路由到localhost:18085的时候去掉api
          filters:
            #将请求路径的第一个路径去掉在路由到指定域名去，一个/分割一个路径
          - StripPrefix= 1
            # 给用户的请求添加路径,并路由到配置的服务器中去
            # - PrefixOath=/brand
            #局部限流过滤器
          - name: RequestRateLimiter
            args:
              #用户身份唯一标识符
              key-resolver: "#{@ipKeyResolver}"
              #每秒允许的请求个数
              redis-rate-limiter.replenishRate: 1
              #允许并发有四个请求[宽限的个数]
              redis-rate-limiter.burstCapacity: 1

        #用户微服务网关配置
        - id: changgou-user-route
          uri: lb://user
          predicates:
          - Path=/api/user/**, /api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
          - StripPrefix= 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.104:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

