server:
  port: 18085
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: search
  data:
    elasticsearch:
      #es集群名称
      cluster-name: my-application
      #es集群ip和端口号
      cluster-nodes: 192.168.211.132:9300
  #添加配置到分布式事务控制组内
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#超时配置
ribbon:
  ReadTimeout: 300000
hystrix:
  command:
    excution:
      isolation:
        thread:
          timeoutMilliseconds: 100000