server:
  port: 18091
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.211.132
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  #添加配置到分布式事务控制组内
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#Hystrix配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果设置为false，则请求超时交给ribbon来处理
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
          strategy: SEMAPHORE
#微信支付交换机和队列
mq:
  pay:
    #发送给哪个交换机
    exchange:
      seckillorder: exchange.seckillorder
    #队列名称
    queue:
      seckillorder: queue.seckillorder
    routing:
      seckillkey: queue.seckillorder
    outTime:
      SeckillKey: seckillQueue
      OutTimeQueue: outTimeQueue
      SeckillQueue: seckillQueue
      SeckillExchange: seckillExchange
